# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Companies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Companies
  pod 'Moya', '~> 14.0'
  pod 'lottie-ios'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'SwiftLint'
  pod 'OxeNetworking'

end
